name: Pull from code.maralorn.de
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Pull main if fast-forward
        run: |
          git pull --ff-only https://code.maralorn.de/maralorn/nix-output-monitor.git main:main
          git push main:main
